# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 15e83c8
_src_path: eed-java-backend-template
github_owner: eed-web-application
project_name: elog-plus
project_slug: elog_plus
