services:
  test:
    image: scr.svc.stanford.edu/eed-development/devops/build-image/build-java/build-java19-alpine:latest
    environment:
      - MINIO_HOST=minio
      - DB_HOST=mongodb-primary
      - WAIT_LOGGER_LEVEL=debug
      - WAIT_TIMEOUT=90
      - WAIT_HOSTS=mongodb-primary:27017, minio:9000
    command: /opt/test/execute-test.sh
    volumes:
      - ./:/opt/test
    networks:
      - back-tier
    depends_on:
      - mongodb-primary
      - minio