logging:
  level:
    edu.stanford.slac.elog_plus: ${ELOG_PLUS_LOG_LEVEL:DEBUG}

server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: 'elog'
  cache:
    type: hazelcast
  ldap:
    urls: ${ELOG_PLUS_LDAP_URI:ldap://localhost:8389}
    base: ${ELOG_PLUS_LDAP_BASE:dc=sdf,dc=slac,dc=stanford,dc=edu}
  data:
    mongodb:
      uri: ${ELOG_PLUS_MONGODB_URI:mongodb://elogs:elogs@localhost:27017/elogs?authSource=elogs}
  kafka:
    bootstrap-servers: ${ELOG_PLUS_KAFKA_BOOTSTRAP:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${ELOG_PLUS_CONSUMER_GROUP_ID:${random.uuid}}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: ${ELOG_PLUS_MAX_POST_SIZE:100MB}
      max-request-size: ${ELOG_PLUS_MAX_POST_SIZE:100MB}

edu:
  stanford:
    slac:
      elog-plus:
        image-preview-topic: ${ELOG_PLUS_IMAGE_PREVIEW_TOPIC:elog-plus-preview-creation}
        storage:
          url: ${ELOG_PLUS_MINIO_URL:http://localhost:9000}
          key: ${ELOG_PLUS_MINIO_KEY:minio}
          secret: ${ELOG_PLUS_MINIO_SECRET:minio123}
          bucket: ${ELOG_PLUS_MINIO_BUCKET_NAME:elog}
      ad:
        eed:
          baselib:
            app-token-prefix: ${spring.application.name}
            app-token-jwt-key: ${ELOG_PLUS_APP_TOKEN_JWT_KEY:token-header-key}
            user-header-name: ${ELOG_PLUS_AUTH_HEADER:x-vouch-idp-accesstoken}
            oauth-server-discover: ${ELOG_PLUS_OIDC_CONFIGURATION_ENDPOINT:https://dex.slac.stanford.edu/.well-known/openid-configuration}
            root-user-list: ${ELOG_PLUS_ROOT_USERS}
            root-authentication-token-list-json: ${ELOG_PLUS_ROOT_AUTHENTICATION_TOKEN_JSON:[]}
          mongodb:
            db_admin_uri: ${ELOG_PLUS_ADMIN_MONGODB_URI:mongodb://admin:admin@localhost:27017/?authSource=admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
# swagger-ui custom path
springdoc:
  title: 'ELOG management backend'
  description: 'ELOG management backend for the Accelerator Division at SLAC National Accelerator Laboratory'
  contact:
    name: 'API Support'
    url: 'https://confluence.slac.stanford.edu/display/EEDWAD/EED+Web+Applications'
    email: 'bisegni@sac.stanford.edu'
  swagger-ui:
    enabled: false
  api-docs:
    path: /api-docs

mongock:
  migration-scan-package:
    - edu.stanford.slac.elog_plus.migration
  throw-exception-if-cannot-obtain-lock: true #Default true
  track-ignored: false #Default true
  transaction-enabled: false
  runner-type: initializingbean
  enabled: true #Default true