logging:
  level:
    edu.stanford.slac.elog_plus: DEBUG
    org.springdoc: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: 'elog-plus'
  data:
    mongodb:
      uri: mongodb://elogs:elogs@${DB_HOST:localhost}:27017/elogs?authSource=elogs

edu:
  stanford:
    slac:
      elogs-plus:
        minio:
          url: ${MINIO_URL:http://${MINIO_HOST:localhost}:9000}
          key: ${MINIO_KEY:minio}
          secret: ${MINIO_SECRET:minio123}
          bucket: ${MINIO_BUCKET_NAME:elog}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs